src/app/(use-navbar)/page.tsx
src/components/CoachingInfo/CoachingInfo.tsx
src/components/CoachingInfo/Reason99notes.tsx
src/components/Navbar/SearchBar.tsx
src/components/Navbar/navbar.tsx
src/components/common/FAQ/FAQ.tsx

Making the development branch(master) up to date.

Landing Page

---

src/app/(use-navbar)/current-affairs/[category]/[section]/page.tsx
src/app/(use-navbar)/current-affairs/page.tsx
src/components/dashboard/forms/CurrentArticleForm.tsx
src/components/dashboard/forms/index.ts
src/components/dashboard/static/current-affair/PageForm.tsx
src/components/dashboard/static/current-affair/QuizQuestions.tsx
src/components/quiz/QuizWrapper.tsx
src/components/quiz/quiz.tsx
src/components/templates/ArticleTemplate.tsx

Fixed Current Affair/Article metadata addition and Added the add quiz functionality

Addcurrent

---

src/app/(use-navbar)/page.tsx
src/components/CoachingInfo/CoachingInfo.tsx
src/components/CoachingInfo/Reason99notes.tsx
src/components/CurrentAffairs/CurrentAffairs.tsx
src/components/CurrentAffairs/CurrentAffairsCard.tsx
src/components/Navbar/navbar.tsx
src/components/common/FAQ/FAQ.tsx
src/components/common/FAQ/FAQItem.tsx

improved fonts of landing page

Fonts of landing page

---

src/components/Navbar/navbar.tsx

Corrected currnnt affair dropdown font

Corrected Navbar

---

src/app/(no-navbar)/dashboard/editcurrent/articles/page.tsx
src/app/(no-navbar)/dashboard/sort/page.tsx
src/components/dashboard/static/current-affair/PageForm.tsx
src/components/ui/whatsapp.tsx

Tested all features from admin portal. ALL WORKING!
DATE_TIME: Apr 15 19:12

Minor bug fixes

---

src/app/(use-navbar)/subscription/page.tsx

Exception handling to be done. @manvirsingh1716

Payments route handled

---

package-lock.json
package.json
src/app/(no-navbar)/dashboard/addadmin/page.tsx
src/app/(no-navbar)/dashboard/forms/page.tsx
src/app/(no-navbar)/dashboard/layout.tsx
src/app/(no-navbar)/dashboard/manageemployees/page.tsx
src/app/(no-navbar)/dashboard/sort/page.tsx
src/app/(no-navbar)/dashboard/sortCurrent/page.tsx
src/app/(no-navbar)/dashboard/subscription/page.tsx
src/app/(no-navbar)/operator/page.tsx

Improved admin dash ui

---

src/app/(no-navbar)/dashboard/manageemployees/page.tsx
src/app/(use-navbar)/current-affairs/[category]/[section]/page.tsx
src/app/(use-navbar)/current-affairs/[category]/page.tsx
src/app/(use-navbar)/current-affairs/page.tsx
src/app/(use-navbar)/page.tsx
src/components/CoachingInfo/CoachingInfo.tsx
src/components/CurrentAffairs/CurrentAffairsLayout.tsx
src/components/Navbar/navbar.tsx
src/components/common/ContactForm/ContactForm.tsx
src/styles/globals.css

Improved ui to match 99notes Mainly current affair

Improved ca  ui

---

src/app/(no-navbar)/dashboard/edit/page.tsx
src/app/(no-navbar)/dashboard/editblogs/page.tsx
src/app/(use-navbar)/about/page.tsx
src/app/(use-navbar)/blog/[blogs]/page.tsx
src/app/(use-navbar)/blog/page.tsx
src/app/(use-navbar)/page.tsx
src/components/Blogs/BlogCard.tsx
src/components/CurrentAffairs/CurrentAffairsLayout.tsx
src/components/Navbar/navbar.tsx
src/components/StudyMaterials/Studymaterials.tsx
src/components/common/Contact/ContactMap.tsx
src/components/dashboard/forms/BlogForm.tsx
src/components/dashboard/forms/CurrentArticleForm.tsx
src/components/navigation/Assistivetouch.tsx
src/components/templates/ArticleTemplate.tsx
src/components/templates/BlogTemplate.tsx
src/components/templates/GeneralStudiesTemplate.tsx
src/components/templates/UpscNotesTemplate.tsx
src/styles/globals.css

changes on admin

---

src/app/(no-navbar)/dashboard/editblogs/page.tsx
src/components/Navbar/navbar.tsx
src/components/dashboard/forms/ArticleForm.tsx
src/components/dashboard/forms/BlogForm.tsx
src/components/dashboard/forms/CurrentAffairForm.tsx
src/components/dashboard/forms/CurrentArticleForm.tsx
src/components/dashboard/forms/GeneralStudiesForm.tsx
src/components/dashboard/forms/UPSCNotesForm.tsx

Updater alert on admin
updated global css
Fixed some small css error

Updaed admin alerts and ui

---

src/app/(use-navbar)/page.tsx
src/components/Navbar/navbar.tsx
src/components/dashboard/forms/CustomLinkForm.tsx
src/components/templates/ArticleTemplate.tsx

Added hamburger of small screen
improved  spacing between elements

Improved navbar ui

---

src/app/(use-navbar)/blog/page.tsx
src/app/(use-navbar)/current-affairs/[category]/page.tsx
src/app/(use-navbar)/page.tsx
src/components/CurrentAffairs/CurrentAffairsLayout.tsx
src/components/Navbar/navbar.tsx
src/components/templates/UpscNotesTemplate.tsx

Updated layout

---

src/app/(no-navbar)/dashboard/editblogs/page.tsx
src/app/(use-navbar)/blog/page.tsx
src/components/Blogs/relatedTopics.tsx
src/components/Navbar/navbar.tsx
src/components/templates/ArticleTemplate.tsx
src/components/ui/tiptapeditor.tsx
src/styles/globals.css

ui correction

---

src/components/ui/tiptapeditor.tsx

Added coustom css for the table in the html editor

added table

---

src/app/(use-navbar)/tag/[slug]/page.tsx

Tag page ui

---

src/app/(no-navbar)/dashboard/addquestions/page.tsx
src/app/(use-navbar)/quiz/page.tsx
src/components/quiz/quiz.tsx

Added index in question in quiz

Add question index

---

src/app/(no-navbar)/dashboard/addquestions/page.tsx

Add-que-ui

---

src/components/ui/tableDesigns.ts
src/components/ui/tiptapeditor.tsx

Added Deafault table

---

package-lock.json
package.json
src/components/navigation/TableOfContents.tsx

Only h2 at toc

---

src/app/(use-navbar)/quiz/page.tsx
src/components/quiz/quiz.tsx

The flow for the Quiz on main website done

quizonmainwebsite

---

src/app/(no-navbar)/dashboard/addquestions/page.tsx
src/components/dashboard/forms/ArticleForm.tsx
src/components/dashboard/forms/BlogForm.tsx
src/components/dashboard/forms/CurrentAffairPageForm.tsx
src/components/dashboard/forms/CurrentArticleForm.tsx
src/components/dashboard/forms/GeneralStudiesForm.tsx

Removed image url and improved add q ui

Removed image url and improved add q ui

---

src/app/(no-navbar)/dashboard/addquestions/page.tsx
src/app/(no-navbar)/dashboard/adminpermissions/page.tsx
src/components/quiz/quiz.tsx
src/components/templates/ArticleTemplate.tsx

practice more flow and improved some page ui

worked practice more and some page ui

---

src/components/quiz/quiz.tsx
src/components/templates/ArticleTemplate.tsx
src/components/templates/GeneralStudiesTemplate.tsx

Directly questioon will be shown on the page

direct question on page

---

package-lock.json
package.json
src/components/ui/tiptapeditor.tsx

Resolved Table Issues

---

package-lock.json
package.json
src/components/ui/tiptapeditor.tsx
src/styles/globals.css

task 4and5

---

src/app/(use-navbar)/current-affairs/[category]/[section]/page.tsx
src/components/navigation/TableOfContents.tsx
src/components/templates/ArticleTemplate.tsx
src/styles/globals.css

Blogs and toc for the current affairs

Blogs toc and its tag

---

src/components/templates/GeneralStudiesTemplate.tsx

Image css on gs

---

src/components/ui/tiptapeditor.tsx

RE applying indentation and subindentation

Reapplying indentation

---

src/components/ui/tiptapeditor.tsx
src/styles/globals.css

Table-scrolling Horizontal

---

src/components/ui/tiptapeditor.tsx
src/styles/globals.css

These are the final for side image

Final side Image

---

src/app/(no-navbar)/dashboard/addadmin/page.tsx
src/app/(no-navbar)/dashboard/manageusers/page.tsx
src/app/(no-navbar)/dashboard/subscription/page.tsx
src/components/templates/ArticleTemplate.tsx
src/components/ui/downloadpdf.tsx
src/components/ui/whatsapp-pdf.tsx

Whatsapp and download button

---

src/app/(use-navbar)/search-result/page.tsx
src/components/Navbar/SearchBar.tsx
src/components/Navbar/navbar.tsx
src/components/ui/tiptapeditor.tsx

Image in table does not disappear

Image in table issue
